const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const gitignorePath = path.join(rootDir, '.gitignore');
const distignorePath = path.join(rootDir, '.distignore');
const gitattributesPath = path.join(rootDir, '.gitattributes');

// Base files and folders that are tracked in Git but must NEVER be distributed in release packages
const distOnly = [
    '/.git',
    '/.github',
    '/.gitignore',
    '/.gitattributes',
    '.distignore',
    '/dev',
    '/dev_llm',
    '/tests',
    '/assets/screenshots',
    'phpunit.xml.dist',
    '.phpunit.result.cache',
    '.phpunit.cache',
    'composer.json',
    'composer.lock',
    'package.json',
    'package-lock.json',
    'vendor',
    'node_modules',
    'AGENTS.md',
    '.agents',
    'agent_memory.md',
    'TODO.md',
    'todo.php'
];

function sync() {
    let gitignoreRules = [];
    if (fs.existsSync(gitignorePath)) {
        const content = fs.readFileSync(gitignorePath, 'utf8');
        gitignoreRules = content
            .split(/\r?\n/)
            .map(line => line.trim())
            .filter(line => line && !line.startsWith('#'));
    }

    const normalizedSet = new Map();

    const addRule = (rawRule) => {
        const trimmed = rawRule.trim();
        if (!trimmed || trimmed.startsWith('#')) return;
        const cleanKey = trimmed.replace(/^\/+/, '').replace(/\/+$/, '');
        if (!normalizedSet.has(cleanKey)) {
            normalizedSet.set(cleanKey, trimmed);
        }
    };

    // Add dist-only first
    distOnly.forEach(addRule);
    // Add .gitignore rules
    gitignoreRules.forEach(addRule);

    const sortedRules = Array.from(normalizedSet.values()).sort((a, b) => a.localeCompare(b));

    const distContent = [
        '# ====================================================================',
        '# AUTO-GENERATED BY dev/sync-ignore.js - DO NOT EDIT DIRECTLY',
        '# Synced from .gitignore + distribution-only exclusions',
        '# Run "npm run sync:ignore" to regenerate',
        '# ====================================================================',
        '',
        ...sortedRules,
        ''
    ].join('\n');

    fs.writeFileSync(distignorePath, distContent, 'utf8');
    console.log('✅ Synced .distignore with .gitignore and distribution exclusions.');

    // Ensure .distignore is also in .gitattributes as export-ignore
    if (fs.existsSync(gitattributesPath)) {
        let attrContent = fs.readFileSync(gitattributesPath, 'utf8');
        if (!attrContent.includes('.distignore export-ignore')) {
            attrContent = attrContent.trimEnd() + '\n/.distignore            export-ignore\n';
            fs.writeFileSync(gitattributesPath, attrContent, 'utf8');
            console.log('✅ Added .distignore to .gitattributes (export-ignore).');
        }
    }
}

if (require.main === module) {
    sync();
}

module.exports = sync;
